In [1]:
import numpy as np

In [4]:
null_vector = np.zeros(10)
print (null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
null_vector[4] = 1
print (null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [16]:
b = np.flip(a)
#b = a[::-1]
print(b)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [13]:
mat = np.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
ele = np.array([1, 2 , 0,  0,  4,  0])
non = np.where(ele > 0.0)
print(non)

(array([0, 1, 4]),)


In [24]:
random_vec = np.random.random(size = 30)
print (len(random_vec))
mean = np.mean(random_vec)
print('mean:',mean)

30
mean: 0.5031847571405218


In [35]:
array_2D = np.zeros((2,6))
array_2D[:,-1] = 1
array_2D[:, 0] = 1
print(array_2D)

[[1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]]


In [40]:
checker = np.zeros((8,8), dtype = int)
checker[::2, ::2] = 1
checker[1::2, 1::2] = 1
print(checker)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [52]:
#a = np.array([1,0,0,1]).reshape(2,2)
a = np.array([[1,0],[0,1]])
check_tile = np.tile(a, (4,4))
#print(a)
print(check_tile)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [56]:
Z = np.arange(11)
Z =  -1.0 * Z
print(Z)

[ -0.  -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.  -9. -10.]


In [59]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = (A == B)
print(equal)

[ True  True False False  True]


In [60]:
Z = np.arange(10, dtype=np.int32)
print(Z.dtype)
Z **= 2
print(Z.dtype)

int32
int32


In [64]:
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D = np.diag(C)
print(D)

[ 18  66 132]
